import{a as v,S,i}from"./assets/vendor-CesYmgD5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="57471701-99d02be1d10482722832ebff7";async function f(o,e){const{data:r}=await v.get("https://pixabay.com/api/",{params:{key:q,q:o,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r}const d=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");console.log(d);console.log(h);const M=new S(".gallery a");function m(o){const e=o.map(r=>`<li>
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" width="360" height="300"/>
      </a>
      <p>${r.likes}</p>
      <p>${r.views}</p>
      <p>${r.comments}</p>
      <p>${r.downloads}</p>
    </li>`).join("");d.insertAdjacentHTML("beforeend",e),M.refresh()}function P(){d.innerHTML=""}function g(){h.classList.add("is-active")}function p(){h.classList.remove("is-active")}function L(){y.classList.add("is-active")}function u(){y.classList.remove("is-active")}const w=document.querySelector(".form"),b=document.querySelector(".load-more");console.log(w);console.log(b);w.addEventListener("submit",$);b.addEventListener("click",B);let n="",a=1;async function $(o){if(o.preventDefault(),n=o.currentTarget.elements["search-text"].value.trim(),n!==""){a=1,u(),P(),g();try{const e=await f(n,a);if(e.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!"});return}m(e.hits),e.totalHits>e.hits.length&&L()}catch{i.show({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{p()}}}async function B(){a+=1,g(),u();try{const o=await f(n,a);m(o.hits);const e=document.querySelector(".gallery li"),{height:r}=e.getBoundingClientRect();if(window.scrollBy({top:r*2,behavior:"smooth"}),a*15>=o.totalHits||o.hits.length<15){u(),i.show({message:"We're sorry, but you've reached the end of search results."});return}L()}catch{i.show({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{p()}}
//# sourceMappingURL=index.js.map
