import{a as v,S,i as a}from"./assets/vendor-CesYmgD5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const q="57471701-99d02be1d10482722832ebff7";async function f(r,e){const{data:o}=await v.get("https://pixabay.com/api/",{params:{key:q,q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return o}const d=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");console.log(d);console.log(h);const M=new S(".gallery a");function m(r){const e=r.map(o=>`<li>
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" width="360" height="300"/>
      </a>
      <p>Likes ${o.likes}</p>
      <p>Views ${o.views}</p>
      <p>Comments ${o.comments}</p>
      <p>Downloads ${o.downloads}</p>
    </li>`).join("");d.insertAdjacentHTML("beforeend",e),M.refresh()}function P(){d.innerHTML=""}function g(){h.classList.add("is-active")}function p(){h.classList.remove("is-active")}function L(){y.classList.add("is-active")}function u(){y.classList.remove("is-active")}const w=document.querySelector(".form"),b=document.querySelector(".load-more");console.log(w);console.log(b);w.addEventListener("submit",$);b.addEventListener("click",B);let i="",n=1;async function $(r){if(r.preventDefault(),i=r.currentTarget.elements["search-text"].value.trim(),i!==""){n=1,u(),P(),g();try{const e=await f(i,n);if(e.hits.length===0){a.show({message:"Sorry, there are no images matching your search query. Please try again!"});return}m(e.hits),e.totalHits>e.hits.length?L():a.show({message:"We're sorry, but you've reached the end of search results."})}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{p()}}}async function B(){n+=1,g(),u();try{const r=await f(i,n);m(r.hits);const e=document.querySelector(".gallery li"),{height:o}=e.getBoundingClientRect();if(window.scrollBy({top:o*2,behavior:"smooth"}),n*15>=r.totalHits||r.hits.length<15){u(),a.show({message:"We're sorry, but you've reached the end of search results."});return}L()}catch{a.show({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{p()}}
//# sourceMappingURL=index.js.map
